import React from 'react'


export const metadata = {
  title: 'Chat App | Nextjs',
  description: 'Generated by create next app',
}

export const revalidate = 0

export const dynamic = "force-dynamic"
function page() {
  return (
   <div>dfsdfsg</div> 
  )
}

export default page